# Diseño del Instrumento {#dis_ins}

A continuación se presenta el desarrollo del cuestionario del ELSOC. El instrumento de recolección de información consiste en un cuestionario estructurado (tipo encuesta) aplicado cara a cara a todos los participantes. Dicha aplicación se hace utilizando el sistema *CAPI* (Encuestas personales asistidas por computadores). El cuestionario fue diseñado para medir una serie de aspectos conceptualmente  relevantes que permiten caracterizar los niveles  de conflicto y cohesión social en Chile, enfatizando su evolución a lo largo del tiempo. Los principales temas de interés analítico abordados por la encuesta corresponden a los módulos en los cuales se estructura:

1. **Ciudadanía y Democracia.**
2. **Redes sociales e Interacciones inter-grupales.**
3. **Legitimidad y desigualdad social.**
4. **Conflicto social.**
5. **Dimensión barrial y territorial.**
6. **Salud y bienestar.**
7. **Caracterización Socio demográfica.**

## Proceso de Diseño {#proc-dis}
El proceso de diseño del cuestionario de ELSOC se desarrolló durante el año 2015 y abarcó las olas 2016 y 2017. Por lo tanto, el proceso de trabajo aquí descrito coincide con el presentado en el Manual de Usuario de ELSOC 2016. Las diferencias entre ambos cuestionarios son descritas en el siguiente apartado.

La mayoría de las preguntas, escalas y/o items incluidos en los módulos de ELSOC 2017 provienen de otros estudios de opinión pública, investigaciones -en psicología, sociología, economía, ciencia política- realizadas por académicos nacionales e internacionales y encuestas sociales conducidas en Chile y otros países. En forma complementaria, algunas escalas fueron desarrolladas por los miembros del equipo COES y/o han sido adaptadas de estudios anteriores de éstos. De manera genérica, el cuestionario fue diseñado aprovechando las principales recomendaciones técnicas y el estado del arte en las distintas áreas de estudio incluidas.

Con el objetivo de satisfacer los criterios y estándares de calidad para cuestionarios y compatibilizar la multiplicidad de agendas de investigación desarrolladas por COES, se optó por elaborar un procedimiento de trabajo para la construcción de éste. Este proceso se desarrolló durante el año 2015 en distintas fases:


1. Se solicitó a los investigadores vinculados a COES proponer proyectos de investigación que contemplen un planteamiento teórico e hipótesis que fundamenten las escalas propuestas para ser incluidas en el cuestionario. Las propuestas podían ser presentadas de manera individual o colectiva y no existían restricciones en el número de ítems a proponer. Sólo se exigía una fundamentación teórica explícita que involucre hipótesis longitudinales y una operacionalización de los constructos a medir en los distintos items propuestos. 
2. El procedimiento anterior implicó la recepción y organización de un elevado número de agendas de investigación, los que se materializan en más 750 items (preguntas únicas o parte de una escala). El equipo ELSOC sistematizó las propuestas recibidas, clasificando los items en áreas temáticas. A la vez, se diseñaron mecanismos para reducir el número de items y coordinaron reuniones entre los investigadores COES para decidir sobre éstos. Los criterios de selección fueron principalmente teóricos, priorizando las preguntas fundamentales para el análisis longitudinal de los proyectos de investigación como su concordancia con la agenda sustantiva de COES ^[También se incluyeron criterios prácticos, relativos a la eliminación de items idénticos o muy semejantes; evidencia previa sobre la calidad de los items (encuestas anteriores, especialmente la encuesta de corte transversal desarrollada por COES el año 2014) y el diseño general del estudio (diseño muestral, unidad de análisis, tipo de informante, etc.).].

3. Luego de una selección de las escalas más relevantes para cada tema propuesto, se realizó un estudio piloto del cuestionario desarrollado. Esto implicó pilotear 430 items, donde el Centro MicroDatos de la Universidad de Chile se encargó de su ejecución. En base a los resultados de dicho piloto, el equipo panel realizó ajustes a algunos items y elaboró una propuesta de reducción de ítems que fue evaluada con los investigadores del Centro. 

4. La última etapa de ajuste del cuestionario se centró en identificar los aspectos conceptualmente más relevantes para COES y ponderar los requerimientos metodológicos para su evaluación empírica. De este modo, se clasificaron los items según el número de mediciones requeridas, distinguiendo entre items permanentes (que serán medidos en todas las olas, ya que constituyen el núcleo analítico del estudio) e  intercalados (que serán medidos una única vez o una ola por medio). 


La versión final del instrumento de recolección de información consiste en un cuestionario estructurado (tipo encuesta) que se aplica cara a cara a todos los participantes con una periodicidad anual. Sin embargo, debe tenerse presente que existen diferencias entre los cuestionarios de las distintas olas producto de la inclusión de los items intercalados ^[Algunos items aparecen una única vez (características invariantes en el tiempo) y otros son rotados (aparecen en años pares o impares).]. Luego, en el Cuadro \ref{table:items} se resumen los conceptos que se incluyeron en las distintas secciones del cuestionario de ELSOC 2017. Para más detalles sobre el Cuestionario se debe revisar la sección de Libro de Códigos.

\newpage
## Diferencias entre Cuestionarios de Ola 1 y 2 {#dif-cuest}
Para examinar de manera pormenorizada las diferencias entre los instrumentos aplicados en 2016 y 2017 se sugiere a los interesados revisar tanto los cuestionarios como los libros de códigos asociadoos a cada estudio. A su vez, el *Listado de Variables* incluido es una guía útil para contrastar los cuestionarios, siendo relevante enfocarse en los *items intercalados, áquellos incluidos año por medio o una única vez en ELSOC.* De todos modos, el Cuadro \ref{{tab:difcuest}} señala algunas diferencias entre ambos cuestionarios.

Un tema relacionado es la duración promedio de la entrevista. Durante 2016 la duración promedio por encuestado fue de 55 minutos. CMD solicitó al equipo ELSOC tratar dicho lapso temporal a 45 minutos promedio, motivo por el cual se recomendaba acortar la extensión del estudio. El Equipo ELSOC, en conjunto con investigadores COES definió distintos ajustes que permitieron reducir la extensión del cuestionario. Mientras el cuestionario de la ola 2016 contenía 336 items, en el año 2017 el instrumento contemplaba 317 items.

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(pacman)
pacman::p_load(tidyverse,knitr,kableExtra,dplyr,tinytex)

temas_conceptos <- 


temas_conceptos %>%
  kable(booktabs = TRUE,caption="\\label{tab:difcuest}Temas y Conceptos medidos en ELSCO Ola 1") %>%
  column_spec(c(1), width = "2cm") %>%
  column_spec(c(2), width = "8cm") %>%
  landscape()
```

Falta Revisar: REFERENCIAS A TABLAS + VER TABLA
