# Registro de Versiones Base de Datos {#registrosver}

Las versiones adjuntadas de la base de datos, como el presenteManual de Usuario fueron elaborados por el Equipo de Encuestas COES. Sin embargo, **no pueden ser consideradas como definitivas**, ya que como equipo estamos constantemente revisando la calidad de éstos. En caso que como usuario detecté problemas con la base de datos, comuníquese con encuestacoes@gmail.com. A su vez, los miembros del listado de emails de ELSOC recibirán, en caso de que sean necesarios, los cambios introducidos en el estudio. **Ni las bases de datos ni el Manual pueden ser entregados a terceros que no sean parte de COES**. Los datos y documentos deben ser obtenidos desde el sitio oficial del estudio. En esta sección se resumen las versiones existentes, a la fecha, de la base de datos correspondiente a la primera ola del estudio longitudinal (Ver Cuadro \@ref(tab:versiones)). A su vez, se reseñan las diferencias entre dichas versiones y los cambios introducidos.


## Casos Falsificados {#casosfal}

Durante la realización del trabajo de campo de ELSOC 2018, el equipo de Centro Micro Datos, junto al equipo de Encuestas COES detectó que 56 entrevistas correspondientes a la ola 2016 fueron falsificadas. Producto de lo anterior, dichas respuestas fueron eliminadas de la base de datos en la versión 3.0 del 28 de Diciembre de 2018. El problema representa menos del 1% del tamaño muestral original y, en los análisis realizados por el equipo de Encuestas COES, no se detectaron cambios sustantivos en la distribución de las variables tras su eliminación.

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(pacman)
pacman::p_load(tidyverse,knitr,kableExtra,dplyr,tinytex)

versiones <- tibble(Versión = c("0.0"),
                  "Fecha" = c("20/12/2016"),        
                  "Nombre Archivo" = c("BBDD COES Entrega 1"),
                  "Características" = c("Base original entregada por Centro 
                                        Micro Datos a COES. Contiene
                                        respuestas de 2983 entrevistados (N final)
                                        a preguntas del cuestionario.")) %>% 
  add_row(Versión = c("0.5"),
                  "Fecha" = c("12/01/2017"),        
                  "Nombre Archivo" = c("Base Datos Entrevistado 20170111"),
                  "Características" = c("Base de datos ajustada a solicitudes
                                        de COES: nuevos nombres variables,
                                        reetiquetamiento, ajuste de valores
                                        perdidos. Variables de sexo y edad.")) %>% 
    add_row(Versión = c("1.0"),
                  "Fecha" = c("23/03/2017"),        
                  "Nombre Archivo" = c("COESW1_Stata14_V3"),
                  "Características" = c("Base de datos elaborada por COES
                                        uniendo información de ponderadores 
                                        provistos por CMD.")) %>% 
     add_row(Versión = c("2.0"),
                  "Fecha" = c("23/04/2018"),        
                  "Nombre Archivo" = c("ELSOC_W01_v2.00"),
                  "Características" = c("Base de datos elaborada por COES con 
                                        correcciones introducidas durante 2017 y
                                        homologación con base de ELSOC ola 2.")) %>% 
      add_row(Versión = c("3.0"),
                  "Fecha" = c("28/12/2018"),        
                  "Nombre Archivo" = c("ELSOC_W01_v3.00"),
                  "Características" = c("Base de datos elaborada por COES con
                                        correcciones introducidas tras eliminación 
                                        de 56 entrevistas falsificadas."))

versiones %>%
  kable(booktabs = TRUE,longtab=T,  
        caption="\\label{tab:versiones}Versiones de Base de Datos ELSOC Ola 1 (2016)") %>%
  
  kable_styling(latex_options = "HOLD_position") %>%
  column_spec(c(1), width = "1cm") %>%
  column_spec(c(2), width = "1,5cm") %>%
  column_spec(c(3), width = "4cm") %>%
  column_spec(c(4), width = "8cm") %>%
  row_spec(0:5, background = "white") %>% 
  kable_classic(full_width = F)

```


